### PR TITLE
Crops 36 blog adjustments

### PR DESCRIPTION
**Pull request by juampy72**
Needs https://github.com/jrearick/luggage_blog/pull/4

### CODE REVIEW

**Comment by jrearick** [comment]
I am unable to get this to work with a clean build of luggage. When installed with luggage_aliases. Biggest issue is that the Manage Display form is broken (admin/structure/types/manage/people/display/full). It's Missing "Contact" field group, any field re-ordering causes it go go into the "Content" field group. Also generates an error:

```
Notice: Undefined index: name in _field_ui_reduce_order() (line 81 of /Users/jrearick/Sites/luggage_isu_bit/modules/field_ui/field_ui.admin.inc).
```

**Comment by juampy72** [comment]
> I am unable to get this to work with a clean build of luggage.

@jrearick, did you install a clean luggage, then checked out https://github.com/jrearick/luggage_blog/pull/4 and then checked out this branch? I can't think what may be wrong off the top of my head but tomorrow I will rebuild this locally to remember what I was doing because my faulty memory does not even remember what was about.

**Comment by jrearick** [comment]
yeah, still happens with luggage_blog's PR included on my machine. However, luggage_people should not depend on luggage_blog. luggage_blog can require luggage_people though.

**Comment by juampy72** [comment]
> I am unable to get this to work with a clean build of luggage.

@jrearick, I am using https://bitbucket.org/isubit/crops as the core installation. Should I make this to work for luggage?

**Comment by jrearick** [comment]
Merged into crops branch instead of master. https://github.com/isubit/luggage_people/pull/9

**Pull request closed without merging**
